### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by academikuser** [fractaledmind/alfred_bibquery#3]
Hi, your libgen search works for me, but I changed the first part to http://libgen.io/ads.php?    Open Alfred, type li TAB hamlet . return, the browser opens.  For this I type bi and can launch bibdesk, I don't get an entry for bib query or a way to search from Alfred 3.3.1 Does this search multiple .bib files?

**Comment by fractaledmind** [comment]
I have not used or updated this software in a long time, unfortunately, and so I cannot speak with any confidence on whether this works with Alfred 3.

As for how it _was_ _supposed_ to work, you could read the project description [here](http://fractaledmind.com/projects/bibquery/)

**Comment by academikuser** [comment]
Thank you, can confirm still works, bib Spacebar citekey or Author name or part of title.  Thanks!
